/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.exampro.view;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import lk.ijse.exampro.controller.ManageQuestionController;
import lk.ijse.exampro.controller.ManageSubjectsController;
import lk.ijse.exampro.dto.QuestionDTO;
import lk.ijse.exampro.dto.SubjectsDTO;

/**
 *
 * @author Hafees
 */
public class ManageQuestion extends javax.swing.JFrame {

    /**
     * Creates new form ManageQuestion_1
     */
    public ManageQuestion() {
        initComponents();
        setSize(1368,767);
        loadAllsubids();
        loadAllquestion();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_cancel3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuestion = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        name_lbl1 = new javax.swing.JLabel();
        txtquestion = new javax.swing.JTextField();
        name_lbl3 = new javax.swing.JLabel();
        txtoption1 = new javax.swing.JTextField();
        Option2 = new javax.swing.JLabel();
        txtoption2 = new javax.swing.JTextField();
        name_lbl2 = new javax.swing.JLabel();
        txtoption3 = new javax.swing.JTextField();
        email_lbl6 = new javax.swing.JLabel();
        txtanswers = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        mobilphn_lbl2 = new javax.swing.JLabel();
        cmbsubjectid = new javax.swing.JComboBox<>();
        email_lbl7 = new javax.swing.JLabel();
        txtsubname = new javax.swing.JTextField();
        id_lbl = new javax.swing.JLabel();
        txtquestid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 3, true));

        jPanel1.setBackground(new java.awt.Color(51, 72, 180));

        btn_cancel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_cancel3.setForeground(new java.awt.Color(51, 102, 255));
        btn_cancel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FontAwesome_f00d(0)_48.png"))); // NOI18N
        btn_cancel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        btn_cancel3.setBorderPainted(false);
        btn_cancel3.setContentAreaFilled(false);
        btn_cancel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancel3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FontAwesome_f00d(0)_48_1.png"))); // NOI18N
        btn_cancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancel3ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minim ize.png"))); // NOI18N
        jButton9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minim ize.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Question");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_new.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_new.setForeground(new java.awt.Color(255, 255, 255));
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_e003(0)_32.png"))); // NOI18N
        btn_new.setText("New");
        btn_new.setContentAreaFilled(false);
        btn_new.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icomoon_e617(0)_48.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.setContentAreaFilled(false);
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_270e(0)_48.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setContentAreaFilled(false);
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_e729(0)_48.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setContentAreaFilled(false);
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_27f3(0)_48.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setContentAreaFilled(false);
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btn_new)
                .addGap(121, 121, 121)
                .addComponent(btn_save)
                .addGap(111, 111, 111)
                .addComponent(btn_update)
                .addGap(160, 160, 160)
                .addComponent(btn_delete)
                .addGap(153, 153, 153)
                .addComponent(btn_clear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_clear))
                .addContainerGap())
        );

        tblQuestion.setBackground(new java.awt.Color(0, 0, 255));
        tblQuestion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblQuestion.setForeground(new java.awt.Color(255, 0, 255));
        tblQuestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Id", "Subject Name", "Questionid", "Question ", "Option 1", "Option 2", "Option 3", "Answers"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblQuestion.setGridColor(new java.awt.Color(0, 0, 255));
        tblQuestion.setOpaque(false);
        tblQuestion.setSelectionForeground(new java.awt.Color(51, 255, 51));
        tblQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuestionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblQuestion);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Question", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        name_lbl1.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        name_lbl1.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl1.setText("Question :");

        txtquestion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtquestion.setBorder(null);
        txtquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquestionActionPerformed(evt);
            }
        });
        txtquestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtquestionKeyReleased(evt);
            }
        });

        name_lbl3.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        name_lbl3.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl3.setText("Option 1 :");

        txtoption1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtoption1.setBorder(null);
        txtoption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoption1ActionPerformed(evt);
            }
        });

        Option2.setBackground(new java.awt.Color(255, 255, 255));
        Option2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Option2.setForeground(new java.awt.Color(0, 0, 204));
        Option2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Option2.setText("Option 2 :");

        txtoption2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtoption2.setBorder(null);

        name_lbl2.setBackground(new java.awt.Color(255, 255, 255));
        name_lbl2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        name_lbl2.setForeground(new java.awt.Color(0, 0, 204));
        name_lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl2.setText("Option 3 :");

        txtoption3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtoption3.setBorder(null);
        txtoption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoption3ActionPerformed(evt);
            }
        });

        email_lbl6.setBackground(new java.awt.Color(255, 255, 255));
        email_lbl6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        email_lbl6.setForeground(new java.awt.Color(0, 0, 204));
        email_lbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_lbl6.setText("Answers :");

        txtanswers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtanswers.setBorder(null);

        jSeparator3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        jSeparator4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        jSeparator5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        jSeparator6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        jSeparator7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(name_lbl3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(Option2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(name_lbl1))
                            .addComponent(name_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtoption1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtoption2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtoption3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtanswers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtquestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtoption1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtoption2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtoption3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtanswers, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(name_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(name_lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Option2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(name_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(email_lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Subject", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        mobilphn_lbl2.setBackground(new java.awt.Color(255, 255, 255));
        mobilphn_lbl2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        mobilphn_lbl2.setForeground(new java.awt.Color(0, 0, 204));
        mobilphn_lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobilphn_lbl2.setText("Subject Id");

        cmbsubjectid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        cmbsubjectid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsubjectidItemStateChanged(evt);
            }
        });
        cmbsubjectid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsubjectidActionPerformed(evt);
            }
        });

        email_lbl7.setBackground(new java.awt.Color(255, 255, 255));
        email_lbl7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        email_lbl7.setForeground(new java.awt.Color(0, 0, 204));
        email_lbl7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email_lbl7.setText("Subject Name");

        txtsubname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtsubname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsubname.setBorder(null);

        id_lbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        id_lbl.setForeground(new java.awt.Color(0, 0, 204));
        id_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        id_lbl.setText("Question ID :");

        txtquestid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtquestid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtquestid.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mobilphn_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbsubjectid, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(txtquestid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(email_lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsubname, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mobilphn_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbsubjectid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(email_lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsubname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtquestid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquestionActionPerformed
        txtoption1.requestFocus();
    }//GEN-LAST:event_txtquestionActionPerformed

    private void txtquestionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquestionKeyReleased
        //Validation.name(txtquestion);
    }//GEN-LAST:event_txtquestionKeyReleased

    private void txtoption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoption3ActionPerformed

    }//GEN-LAST:event_txtoption3ActionPerformed

    private void cmbsubjectidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsubjectidItemStateChanged
        if(cmbsubjectid.getSelectedIndex()!=-1){
            try {
                SubjectsDTO searchSubjects = ManageSubjectsController.searchSubjects(cmbsubjectid.getSelectedItem().toString());

                txtsubname.setText(searchSubjects.getSubjectname());
            } catch (Exception ex) {
                Logger.getLogger(ManageQuestion.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_cmbsubjectidItemStateChanged

    private void cmbsubjectidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsubjectidActionPerformed

    }//GEN-LAST:event_cmbsubjectidActionPerformed

    private void txtoption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoption1ActionPerformed
        txtoption2.requestFocus();
    }//GEN-LAST:event_txtoption1ActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
          clearAllTextFileds();
        btn_save.setEnabled(true);
        btn_new.setEnabled(false);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_clear.setEnabled(false);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String answer = txtanswers.getText();
        String op1 = txtoption1.getText();
        String op2 = txtoption2.getText();
        String op3 = txtoption3.getText();
      
        if(!(answer.equals(op3)||answer.equals(op2)||answer.equals(op1))){
        JOptionPane.showMessageDialog(this, "Please Enter the Answer Match with Given Options \n Note :Letters Are case sensitive");
        txtanswers.requestFocus();
        }else{
        try {
            QuestionDTO questionDTO=new QuestionDTO();
            SubjectsDTO dto=new SubjectsDTO();
            dto.setSubid(Integer.parseInt(cmbsubjectid.getSelectedItem().toString()));
            dto.setSubjectname(txtsubname.getText());
            questionDTO.setSubjectsDTO(dto);
            questionDTO.setQuestion(txtquestion.getText());
            questionDTO.setOption1(txtoption1.getText());
            questionDTO.setOption2(txtoption2.getText());
            questionDTO.setOption3(txtoption3.getText());
            questionDTO.setAnswers(txtanswers.getText());

            boolean addQuestion = ManageQuestionController.addQuestion(questionDTO);
            if(addQuestion){
                UIManager.put("OptionPane.background", Color.WHITE);
                UIManager.getLookAndFeelDefaults().put("Panel.background", Color.WHITE);
                JOptionPane.showMessageDialog(this, "Question saved");
                loadAllquestion();
                clearAllTextFileds();
            }else{
                JOptionPane.showMessageDialog(this, "Question Not saved");

            }
        } catch (Exception ex) {
            Logger.getLogger(ManageQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            QuestionDTO questionDTO=new QuestionDTO();
            SubjectsDTO dto=new SubjectsDTO();
            dto.setSubid(Integer.parseInt(cmbsubjectid.getSelectedItem().toString()));
            dto.setSubjectname(txtsubname.getText());
            questionDTO.setSubjectsDTO(dto);
            questionDTO.setQuestion(txtquestion.getText());
            questionDTO.setOption1(txtoption1.getText());
            questionDTO.setOption2(txtoption2.getText());
            questionDTO.setOption3(txtoption3.getText());
            questionDTO.setAnswers(txtanswers.getText());

            boolean addQuestion = ManageQuestionController.updateQuestion(questionDTO);
            if(addQuestion){
                JOptionPane.showMessageDialog(this, "Question updated");
                  loadAllquestion();
                clearAllTextFileds();
            }else{
                JOptionPane.showMessageDialog(this, "Question Not updated");

            }
        } catch (Exception ex) {
            Logger.getLogger(ManageQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
         clearAllTextFileds();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.setState(ManageQuestion.ICONIFIED);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btn_cancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancel3ActionPerformed
       new AdminWindowNew().setVisible(true);
        dispose();
        // new NewUserForm().dispose();
    }//GEN-LAST:event_btn_cancel3ActionPerformed

    private void tblQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuestionMouseClicked
         try {    
                    if (tblQuestion.getSelectedRow() == -1) return;
                    String subId= tblQuestion.getValueAt(tblQuestion.getSelectedRow(), 0).toString();
                    String subname= tblQuestion.getValueAt(tblQuestion.getSelectedRow(), 1).toString();
                    String quesid= tblQuestion.getValueAt(tblQuestion.getSelectedRow(), 2).toString();
                    String question= tblQuestion.getValueAt(tblQuestion.getSelectedRow(), 3).toString();
                    String op1= tblQuestion.getValueAt(tblQuestion.getSelectedRow(), 4).toString();
                    String op2= tblQuestion.getValueAt(tblQuestion.getSelectedRow(), 5).toString();
                    String op3= tblQuestion.getValueAt(tblQuestion.getSelectedRow(), 6).toString();
                    String answers= tblQuestion.getValueAt(tblQuestion.getSelectedRow(), 7).toString();
                     
                    cmbsubjectid.setSelectedItem(subId);
                    txtsubname.setText(subname);
                    txtquestid.setText(quesid);
                    txtquestion.setText(question);
                    
                    txtoption1.setText(op1);
                    
                    txtoption2.setText(op2);
                    txtoption3.setText(op3);
                    txtanswers.setText(answers);
                  
                } catch (Exception ex) {
                    Logger.getLogger(NewStudentForm_admin.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_tblQuestionMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            boolean result = ManageQuestionController.deleteQuestion((txtquestid.getText()));
            if (result){

                JOptionPane.showMessageDialog(this, "Question has been successfully deleted.");
                loadAllquestion();
                clearAllTextFileds();
            }else{
                JOptionPane.showMessageDialog(this, "Question hasn't been deleted ");
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageQuestion().setVisible(true);
            }
        });
    }
     public void searchQuestion(String qid) throws Exception {
       QuestionDTO questiondto = ManageQuestionController.searchQuestion(qid);
       
       //EmployeeDTO employeedto=ManageEmployeeController.searchEmployee(employeedto);
//        if (questiondto != null) {
//            
//                txtquestion.setText(employeedto.getEmployee_FirstName());
//                txtoption1.setText(employeedto.getEmployee_LastName());
//                txtoption2.setText(employeedto.getEmployee_Gender());
//                //Date date = new Date();
//                //SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
//                //txtDob.setText(dateFormat.format(date));
//              // parseDate(txtDob.setText(employeedto.getDate_Of_Birth()));
//                txtoption3.setText(employeedto.getEmployee_Address());
//                txtSalary.setText(employeedto.getBasic_Salary().toPlainString());
//                txtContact.setText(employeedto.getContact_No());
//                txtEmail.setText(employeedto.getEmployee_Email());
//                txtanswers.setText(employeedto.getPosition());
//        }
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Option2;
    public javax.swing.JButton btn_cancel3;
    public javax.swing.JButton btn_clear;
    public javax.swing.JButton btn_delete;
    public javax.swing.JButton btn_new;
    public javax.swing.JButton btn_save;
    public javax.swing.JButton btn_update;
    public javax.swing.JComboBox<String> cmbsubjectid;
    public javax.swing.JLabel email_lbl6;
    public javax.swing.JLabel email_lbl7;
    public javax.swing.JLabel id_lbl;
    public javax.swing.JButton jButton9;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JSeparator jSeparator6;
    public javax.swing.JSeparator jSeparator7;
    public javax.swing.JLabel mobilphn_lbl2;
    public javax.swing.JLabel name_lbl1;
    public javax.swing.JLabel name_lbl2;
    public javax.swing.JLabel name_lbl3;
    public javax.swing.JTable tblQuestion;
    public javax.swing.JTextField txtanswers;
    public javax.swing.JTextField txtoption1;
    public javax.swing.JTextField txtoption2;
    public javax.swing.JTextField txtoption3;
    public javax.swing.JTextField txtquestid;
    public javax.swing.JTextField txtquestion;
    public javax.swing.JTextField txtsubname;
    // End of variables declaration//GEN-END:variables
private void loadAllsubids(){
    
        try {
            List<SubjectsDTO> allSubjectss = ManageSubjectsController.getAllSubjectss();
            cmbsubjectid.removeAllItems();
            for (SubjectsDTO allSubjects : allSubjectss) {
                int subid = allSubjects.getSubid();
                
                cmbsubjectid.addItem(Integer.toString(subid));
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void loadAllquestion(){
        try {
            List<QuestionDTO> allquestion = ManageQuestionController.getAllQuestions();
            DefaultTableModel dtm=(DefaultTableModel) tblQuestion.getModel();
            dtm.setRowCount(0);
            if(allquestion !=null){
                for (QuestionDTO question : allquestion) {
                    Object []rowdata={
                        question.getSubjectsDTO().getSubid(),
                        question.getSubjectsDTO().getSubjectname(),
                        question.getQid(),
                        question.getQuestion(),
                        question.getOption1(),
                        question.getOption2(),
                        question.getOption3(),
                        question.getAnswers()};
                     dtm.addRow(rowdata);
                }
               
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ManageQuestion.class.getName()).log(Level.SEVERE, null, ex);
    }
}
     private void clearAllTextFileds() {
                 txtsubname.setText("");
                txtquestid.setText("");
                txtquestion.setText("");
                txtoption1.setText("");
                txtoption2.setText("");
                txtoption3.setText("");
                txtanswers.setText("");
                cmbsubjectid.setSelectedIndex(-1);
               
                //lblImage.setIcon(null);
                //txtImagepath.setText("");
                
                // jRadioButton_Male.setSelected(false);
                 //jRadioButton_Female.setSelected(false);
                // jRadioButton1.setSelected(true);
    }
    private void rowSelection(){
     int raw=tblQuestion.getSelectedRow();
     if(raw> -1){
     tblQuestion.setRowSelectionInterval(0, 0);
     }
    }



}
