/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.exampro.view;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.exampro.controller.ManageAdminController;
import lk.ijse.exampro.controller.ManageRegistrationController;
import lk.ijse.exampro.dto.AdminDTO;
import lk.ijse.exampro.dto.RegistrationDTO;
import net.coobird.thumbnailator.Thumbnails;

/**
 *
 * @author Hafees
 */
public class NewStudentForm_admin extends javax.swing.JFrame {
    HashMap<String, String>hashmap=new HashMap<>();
    HashMap<String, RegistrationDTO>hashmapid=new HashMap<>();
    HashMap<String, RegistrationDTO>hashmapname=new HashMap<>();
    HashMap<String, RegistrationDTO>hashmapgender=new HashMap<>(); 
      String filename = null;
      private ImageIcon viewimage=null;
      private ImageIcon formate=null;
      byte[] employeeimage=null; 
      private String gender=null;
      private  String dat=null;
      private boolean useravailablity=false;
    /**
     * Creates new form NewJFrame1
     */
    public NewStudentForm_admin() {
        initComponents();
          //setSize(1368,767);
        //setLocationRelativeTo(null);
        loadRegistration();
//        btn_delete.setEnabled(false);
//        btn_update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_fullname = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_password1 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_chkavailability = new javax.swing.JButton();
        lbl_availability = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_lastname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_email = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txt_phone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txt_username = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblimage = new javax.swing.JLabel();
        txtimagepath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstudents = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btn_new = new javax.swing.JButton();
        btn_save1 = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        TxtSearch = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        cmbsearchby = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JToggleButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        txtdatechooser = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        txt_regid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnupload = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnradiofemale = new javax.swing.JRadioButton();
        btnradiomale = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 4, true));
        jPanel6.setForeground(new java.awt.Color(204, 0, 204));
        jPanel6.setFont(new java.awt.Font("Adobe Arabic", 1, 36)); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Full Name :");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 40));

        jLabel10.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Password :");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 110, 50));

        txt_fullname.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_fullname.setBorder(null);
        jPanel6.add(txt_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 210, 30));

        txt_password.setBorder(null);
        jPanel6.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 220, 30));

        txt_password1.setBorder(null);
        jPanel6.add(txt_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 220, 40));

        jLabel12.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Confirm Password:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 170, 50));

        jPanel2.setBackground(new java.awt.Color(74, 74, 198));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 153, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Registration");

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FontAwesome_f00d(0)_48.png"))); // NOI18N
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 52, 182), 2, true));
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FontAwesome_f00d(0)_48_1.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minim ize.png"))); // NOI18N
        jButton9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minim ize.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FontAwesome_f040(0)_64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 785, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 60));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator1.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);
        jSeparator1.setFont(new java.awt.Font("Adobe Arabic", 1, 36)); // NOI18N
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 220, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator3.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator3.setAlignmentX(2.0F);
        jSeparator3.setAlignmentY(2.0F);
        jSeparator3.setFont(new java.awt.Font("Adobe Arabic", 1, 36)); // NOI18N
        jPanel6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator4.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator4.setAlignmentX(2.0F);
        jSeparator4.setAlignmentY(2.0F);
        jSeparator4.setFont(new java.awt.Font("Adobe Arabic", 1, 36)); // NOI18N
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 220, 10));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 170, 30));

        btn_chkavailability.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        btn_chkavailability.setForeground(new java.awt.Color(0, 0, 153));
        btn_chkavailability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_2753(0)_48.png"))); // NOI18N
        btn_chkavailability.setText("Check Availability");
        btn_chkavailability.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));
        btn_chkavailability.setContentAreaFilled(false);
        btn_chkavailability.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_chkavailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chkavailabilityActionPerformed(evt);
            }
        });
        jPanel6.add(btn_chkavailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 80, 200, 40));

        lbl_availability.setBackground(new java.awt.Color(255, 255, 255));
        lbl_availability.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_availability.setOpaque(true);
        jPanel6.add(lbl_availability, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 340, 30));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DOB :");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator5.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator5.setAlignmentX(2.0F);
        jSeparator5.setAlignmentY(2.0F);
        jSeparator5.setFont(new java.awt.Font("Adobe Arabic", 1, 36)); // NOI18N
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 210, 10));

        txt_lastname.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_lastname.setBorder(null);
        jPanel6.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 200, 30));

        jLabel14.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Email :");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 70, 40));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator7.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator7.setAlignmentX(2.0F);
        jSeparator7.setAlignmentY(2.0F);
        jSeparator7.setFont(new java.awt.Font("Adobe Arabic", 1, 36)); // NOI18N
        jPanel6.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 220, 10));

        txt_email.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_email.setBorder(null);
        jPanel6.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 220, 30));

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Gender :");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 30));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator9.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator9.setAlignmentX(2.0F);
        jSeparator9.setAlignmentY(2.0F);
        jSeparator9.setFont(new java.awt.Font("Adobe Arabic", 1, 36)); // NOI18N
        jPanel6.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 210, 10));

        txt_phone.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_phone.setBorder(null);
        jPanel6.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 210, 30));

        jLabel17.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("User Name :");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 130, 40));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator10.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator10.setAlignmentX(2.0F);
        jSeparator10.setAlignmentY(2.0F);
        jSeparator10.setFont(new java.awt.Font("Adobe Arabic", 1, 36)); // NOI18N
        jPanel6.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 210, 10));

        txt_username.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_username.setBorder(null);
        jPanel6.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 200, 30));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setForeground(new java.awt.Color(204, 204, 204));

        lblimage.setBackground(new java.awt.Color(102, 102, 255));
        lblimage.setOpaque(true);

        jDesktopPane1.setLayer(lblimage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 80, 160, 150));

        txtimagepath.setEditable(false);
        txtimagepath.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(txtimagepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 230, 160, 30));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setText("Image  Path:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 120, 40));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setText("Image :");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 80, 40));

        tblstudents.setForeground(new java.awt.Color(0, 0, 255));
        tblstudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Id", "Full Name", "LastName", "Gender", "DOB", "Email", "Phone", "Image", "Password", "Username"
            }
        ));
        tblstudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstudents);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1370, 260));

        jPanel5.setBackground(new java.awt.Color(23, 23, 143));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_new.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_new.setForeground(new java.awt.Color(255, 255, 255));
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_e003(0)_32.png"))); // NOI18N
        btn_new.setText("New");
        btn_new.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_new.setContentAreaFilled(false);
        btn_new.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        jPanel5.add(btn_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 19, 87, 50));

        btn_save1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save1.setForeground(new java.awt.Color(255, 255, 255));
        btn_save1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icomoon_e617(0)_48.png"))); // NOI18N
        btn_save1.setText("Save");
        btn_save1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_save1.setContentAreaFilled(false);
        btn_save1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save1ActionPerformed(evt);
            }
        });
        jPanel5.add(btn_save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 21, 100, 50));

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_270e(0)_48.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_update.setContentAreaFilled(false);
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel5.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_e729(0)_48.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_delete.setContentAreaFilled(false);
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel5.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 110, -1));

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_27f3(0)_48.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_clear.setContentAreaFilled(false);
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel5.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 110, -1));

        TxtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel5.add(TxtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 39, 132, 29));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SEARCH By");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 6, -1, 25));

        btn_print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FontAwesome_f02f(0)_48.png"))); // NOI18N
        btn_print.setText("Print");
        btn_print.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_print.setContentAreaFilled(false);
        btn_print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel5.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 100, -1));

        cmbsearchby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID" }));
        jPanel5.add(cmbsearchby, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 38, 104, 30));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FontAwesome_f002(0)_48.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel5.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 100, 50));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1370, 90));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jCheckBox2.setText("Show Password");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 130, 30));
        jPanel6.add(txtdatechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 180, 30));

        jLabel18.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Reg Id:");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, 40));

        txt_regid.setEditable(false);
        txt_regid.setBackground(new java.awt.Color(255, 255, 255));
        txt_regid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_regid.setBorder(null);
        jPanel6.add(txt_regid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 210, 30));

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Last  Name :");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 30));

        btnupload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupload.setForeground(new java.awt.Color(0, 0, 204));
        btnupload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Entypo_2b06(0)_48.png"))); // NOI18N
        btnupload.setText("Upload");
        btnupload.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true));
        btnupload.setContentAreaFilled(false);
        btnupload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });
        jPanel6.add(btnupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 280, 150, 40));

        jLabel20.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Phone :");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 40));

        btnradiofemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnradiofemale);
        btnradiofemale.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnradiofemale.setText("Female");
        jPanel6.add(btnradiofemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 80, -1));

        btnradiomale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnradiomale);
        btnradiomale.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnradiomale.setText("Male");
        jPanel6.add(btnradiomale, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
           if(jCheckBox1.isSelected()) {
            txt_password.setEchoChar((char)0);
        } else{
            txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_chkavailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chkavailabilityActionPerformed
         String username = txt_username.getText();
        if(hashmap.containsKey(username)){
            lbl_availability.setText("");
            useravailablity=false;
        lbl_availability.setText("Already Exist!  Try Another User name");
        lbl_availability.setForeground(Color.RED);
        }else{
            useravailablity=true;
             lbl_availability.setText("");
        lbl_availability.setText("Accepted.   Enter The Valid Password in the Password field");
         lbl_availability.setForeground(Color.BLUE);
        }
        
    }//GEN-LAST:event_btn_chkavailabilityActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        clearfields();
        
//        btn_save1.setEnabled(true);
//        btn_new.setEnabled(false);
//        btn_update.setEnabled(false);
//        btn_delete.setEnabled(false);
//        btn_clear.setEnabled(false);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save1ActionPerformed
           if( txt_fullname.getText().equals("")){
            txt_fullname.requestFocus();
            txt_fullname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
            JOptionPane.showMessageDialog(this, "Please Enter the Username");
         }else if(txt_lastname.getText().equals("")){
            txt_lastname.requestFocus();
            JOptionPane.showMessageDialog(this, "Please Enter the Fullname");
          }else if(txtdatechooser.getDate().equals("")){
            txtdatechooser.requestFocus();
            JOptionPane.showMessageDialog(this, "Please Enter the Date of birth");
           }else if(txt_email.getText().equals("")){
            txt_email.requestFocus();
            JOptionPane.showMessageDialog(this, "Please Enter the Email");
           }else if(txt_phone.getText().equals("")){
            txt_phone.requestFocus();
            JOptionPane.showMessageDialog(this, "Please Enter the Phone");
            }else if(txt_username.getText().equals("")){
            txt_username.requestFocus();
            JOptionPane.showMessageDialog(this, "Please Enter the Valid User Name");
            }else if(buttonGroup1.getSelection()==null){
           // txt_username.requestFocus();
           
           
            JOptionPane.showMessageDialog(this, "Please Select The Gender !");
            }else if(useravailablity==false){
            JOptionPane.showMessageDialog(this, "Please  click Check Availabilty  button for Username validation !");
             txt_username.requestFocus();
            }else if(txt_password.getText().equals("")){
            txt_password.requestFocus();
            JOptionPane.showMessageDialog(this, "Please Enter the Password");
             }else if(txt_password1.getText().equals("")){
            txt_password1.requestFocus();
            JOptionPane.showMessageDialog(this, "Please ReEnter the same Password in Confirm password field");
            
            
        }else{
                  if(btnradiomale.isSelected()){
       gender="Male";
       }else{
       gender="Female";
       }

            String userfullname = txt_fullname.getText();
            String userlastname = txt_lastname.getText();
            
            SimpleDateFormat dat=new SimpleDateFormat("yyyy-MM-dd");
        //String date=dat.format(txtDatepicker.getDate());
        String userdob=dat.format(txtdatechooser.getDate());
           // examDTO.setDate(date);
            
            
           // String userdob = txtdatechooser.getText();
            String useremail = txt_email.getText();
            String userphone = txt_phone.getText();
             String username = txt_username.getText();
            char[] pass1 = txt_password.getPassword();
            char[] pass2 = txt_password1.getPassword();
            String pass = String.valueOf(pass2); // most efficient

            //        boolean equals = Arrays.equals(pass2, pass2);
            boolean equals = new String(pass1).equals(new String(pass2));

            if (!equals) {
                JOptionPane.showMessageDialog(this, "Passwords not Match");
                txt_password.requestFocus();
            }else {

                try {
                    
              RegistrationDTO regDTO=new RegistrationDTO();
              regDTO.setFname(userfullname);
              regDTO.setLname(userlastname);
              regDTO.setDob(userdob);
              regDTO.setEmail(useremail);
              regDTO.setPhone(Integer.parseInt(userphone));
              regDTO.setUsername(username);
              regDTO.setPassword(pass);
                    System.out.println("  female "+gender);
              regDTO.setGender(gender);
              regDTO.setUserimage(employeeimage);
             boolean result = ManageRegistrationController.addRegistration(regDTO);                   
                    if (result) {
                        JOptionPane.showMessageDialog(this, "Registration Successfull");
                      loadRegistration();
                      clearfields();
                    } else {
                        JOptionPane.showMessageDialog(this, "Registration fail");
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(NewStudentForm_admin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(NewStudentForm_admin.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
                                           
    }//GEN-LAST:event_btn_save1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        RegistrationDTO regDTO=new RegistrationDTO();
        regDTO.setFname(txt_fullname.getText());
        regDTO.setLname(txt_lastname.getText());
        regDTO.setEmail(txt_email.getText());
        regDTO.setPhone(Integer.parseInt(txt_phone.getText()));
        regDTO.setRegid(Integer.parseInt(txt_regid.getText()));
        regDTO.setUsername(txt_username.getText());
        regDTO.setPassword(txt_password1.getText());
        regDTO.setUserimage(employeeimage);
        
        if(btnradiomale.isSelected()){
       gender="Male";
       }else{
       gender="Female";
       }
        
        regDTO.setGender(gender);
         SimpleDateFormat dat=new SimpleDateFormat("yyyy-MM-dd");
        //String date=dat.format(txtDatepicker.getDate());
        String userdob=dat.format(txtdatechooser.getDate());
        regDTO.setDob(userdob);
        
        
        try {

            boolean result = ManageRegistrationController.updateRegistration(regDTO);
            if (result){
                JOptionPane.showMessageDialog(this, "New User has been successfully updated");
                loadRegistration();
                clearfields();
            }else{
                JOptionPane.showMessageDialog(this, "Updation Failed");
            }

        } catch (Exception ex) {
            Logger.getLogger(NewStudentForm_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
  RegistrationDTO regDTO=new RegistrationDTO();
        regDTO.setFname(txt_fullname.getText());
        regDTO.setLname(txt_lastname.getText());
        regDTO.setEmail(txt_email.getText());
        regDTO.setPhone(Integer.parseInt(txt_phone.getText()));
        regDTO.setRegid(Integer.parseInt(txt_regid.getText()));
        regDTO.setUsername(txt_username.getText());
        regDTO.setFname(txt_password.getText());
        regDTO.setUserimage(employeeimage);
        regDTO.setGender(gender);
         SimpleDateFormat dat=new SimpleDateFormat("yyyy-MM-dd");
        //String date=dat.format(txtDatepicker.getDate());
        String userdob=dat.format(txtdatechooser.getDate());
        regDTO.setDob(userdob);
        
        try {

            boolean result = ManageRegistrationController.deleteRegistration(txt_regid.getText());
            if (result){
                JOptionPane.showMessageDialog(this, "User has been successfully deleted.");
                loadRegistration();
                clearfields();
            }else{
                JOptionPane.showMessageDialog(this, "user hasn't been deleted ");
            }

        } catch (Exception ex) {
            Logger.getLogger(NewStudentForm_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       clearfields();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        tblstudents.setRowSelectionAllowed(true);
    }//GEN-LAST:event_btn_printActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // new AdminWindowNew().setVisible(true);
        this.setVisible(false);
        // close();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.setState(NewStudentForm_admin.ICONIFIED);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox1.isSelected()) {
            txt_password1.setEchoChar((char)0);
        } else{
            txt_password1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
         JFileChooser chooser = new JFileChooser("D:\\Asus Copy\\IJSE\\Semester 2\\Projects\\ExamSimulater Pro\\Exam pro\\Images");
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        txtimagepath.setText(filename);
        
        try {
            
            File image =new File(filename);
            
            BufferedImage thumbanail = Thumbnails.of(image).size(lblimage.getWidth(), lblimage.getHeight()).asBufferedImage();
            
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            
            ImageIO.write(thumbanail, "jpeg", os);
            
            InputStream is = new ByteArrayInputStream(os.toByteArray());
            
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            
            byte[] buf = new byte[1024];  // 1 MB
            
            for(int readNum;(readNum = is.read(buf))!=-1;){
               
            bos.write(buf,0,readNum);
            }
            viewimage=new ImageIcon(thumbanail);
            lblimage.setIcon(viewimage);
            employeeimage=bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnuploadActionPerformed

    private void tblstudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstudentsMouseClicked
         try {    
                    if (tblstudents.getSelectedRow() == -1) return;
//                    btn_delete.setEnabled(true);
//                     btn_update.setEnabled(true);
//                     btn_save1.setEnabled(false);
                    
                    String userId= tblstudents.getValueAt(tblstudents.getSelectedRow(), 0).toString();
                    String userfName= tblstudents.getValueAt(tblstudents.getSelectedRow(), 1).toString();
                    String userLName= tblstudents.getValueAt(tblstudents.getSelectedRow(), 2).toString();
                    String userGender= tblstudents.getValueAt(tblstudents.getSelectedRow(), 3).toString();
                    String userDob= tblstudents.getValueAt(tblstudents.getSelectedRow(), 4).toString();
                    String useremail= tblstudents.getValueAt(tblstudents.getSelectedRow(), 5).toString();
                    String userphone= tblstudents.getValueAt(tblstudents.getSelectedRow(), 6).toString();
                    byte[] userimagedata =(byte[]) tblstudents.getValueAt(tblstudents.getSelectedRow(), 7);
                    String userpass= tblstudents.getValueAt(tblstudents.getSelectedRow(), 8).toString();
                    String username= tblstudents.getValueAt(tblstudents.getSelectedRow(), 9).toString();
                  
                    
                    Date datedob=new SimpleDateFormat("yyyy-MM-dd").parse(userDob);
                     
                    txt_regid.setText(userId);
                    txt_fullname.setText(userfName);
                    txt_lastname.setText(userLName);
                    txt_password1.setText(userpass);
                    
                    txt_username.setText(username);
                    
                    if(userGender.equals("Male")){
                    btnradiomale.setSelected(true);
                    btnradiofemale.setSelected(false);
                    }else{
                     btnradiomale.setSelected(false);
                    btnradiofemale.setSelected(true);
                    }
                    
                    txtdatechooser.setDate(datedob);
                    txt_email.setText(useremail);
                    txt_phone.setText(userphone);
                   
                    formate =new ImageIcon(userimagedata);
                    lblimage.setIcon(formate);
                } catch (ParseException ex) {
                    Logger.getLogger(NewStudentForm_admin.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_tblstudentsMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
              String uid = TxtSearch.getText();
        String selectedItem = cmbsearchby.getSelectedItem().toString();
      
        if(cmbsearchby.getSelectedItem()==null){
           
              JOptionPane.showMessageDialog(this,"Please select Search Type");
              }else if(uid.equals("")){
                  
               JOptionPane.showMessageDialog(this,"Please Entert Type Name");
              }else{
                 
                  if(selectedItem.equalsIgnoreCase("Id")){
       
        
                try {
                   
                        searchUser(uid);
                    } catch (Exception ex) {
                        Logger.getLogger(NewStudentForm_admin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                  }else if(selectedItem.equalsIgnoreCase("Full Name")){
                       System.out.println("  6 ");
                      try {
                          searchUserbyname(uid);
                          System.out.println("  fullname   ");
                      } catch (Exception ex) {
                          Logger.getLogger(NewStudentForm_admin.class.getName()).log(Level.SEVERE, null, ex);
                      }
                  
                  }else if((selectedItem.equalsIgnoreCase("Gender"))){
                       System.out.println("  7 ");
                      try {
                          searchUserbyGender(uid);
                          System.out.println(" gender   ");
                      } catch (Exception ex) {
                          Logger.getLogger(NewStudentForm_admin.class.getName()).log(Level.SEVERE, null, ex);
                      }
                  }
              }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudentForm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudentForm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudentForm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudentForm_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudentForm_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField TxtSearch;
    public javax.swing.JToggleButton btnSearch;
    public javax.swing.JButton btn_chkavailability;
    public javax.swing.JButton btn_clear;
    public javax.swing.JButton btn_delete;
    public javax.swing.JButton btn_new;
    public javax.swing.JButton btn_print;
    public javax.swing.JButton btn_save1;
    public javax.swing.JButton btn_update;
    public javax.swing.JRadioButton btnradiofemale;
    public javax.swing.JRadioButton btnradiomale;
    public javax.swing.JButton btnupload;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cmbsearchby;
    public javax.swing.JButton jButton10;
    public javax.swing.JButton jButton9;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JCheckBox jCheckBox2;
    public javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator10;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JSeparator jSeparator7;
    public javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel lbl_availability;
    public javax.swing.JLabel lblimage;
    public javax.swing.JTable tblstudents;
    public javax.swing.JTextField txt_email;
    public javax.swing.JTextField txt_fullname;
    public javax.swing.JTextField txt_lastname;
    public javax.swing.JPasswordField txt_password;
    public javax.swing.JPasswordField txt_password1;
    public javax.swing.JTextField txt_phone;
    public javax.swing.JTextField txt_regid;
    public javax.swing.JTextField txt_username;
    public com.toedter.calendar.JDateChooser txtdatechooser;
    public javax.swing.JTextField txtimagepath;
    // End of variables declaration//GEN-END:variables

   private void loadRegistration(){
     try {
         List<RegistrationDTO> allreg = ManageRegistrationController.getAllRegistrations();
        
         DefaultTableModel dtm = (DefaultTableModel) tblstudents.getModel();
         dtm.setRowCount(0);
      
         if(allreg!=null){
         for (RegistrationDTO allregs : allreg) {
             Object [] row={allregs.getRegid(),allregs.getFname(),allregs.getLname(),allregs.getGender(),allregs.getDob(),allregs.getEmail(),allregs.getPhone(),allregs.getUserimage(),allregs.getPassword(),allregs.getUsername()};
             dtm.addRow(row);
              hashmap.put(allregs.getUsername(),allregs.getPassword());
            //  hashmapid.put(allregs.getUsername(), allregs);
              hashmapname.put(allregs.getFname(), allregs);
             
              hashmapgender.put(allregs.getGender(), allregs);
             }
         }else{
         return;
         }
     } catch (Exception ex) {
         Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
     }
   }
   
     public void searchUser(String EID) throws Exception {
       RegistrationDTO regdto = ManageRegistrationController.searchRegistration(EID);
        if (regdto != null) {
            gender=regdto.getGender();
            if(gender.equals("Male")){
            btnradiomale.setSelected(true);
            btnradiofemale.setSelected(false);
            }else{
             btnradiomale.setSelected(false);
            btnradiofemale.setSelected(true);
            }
              txt_fullname.setText(regdto.getFname());
             txt_lastname.setText(regdto.getLname());
               
              String date=regdto.getDob();
              Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(date);
              txtdatechooser.setDate(date1);
                txt_email.setText(regdto.getEmail());
                txt_phone.setText(Integer.toString(regdto.getPhone()));
                txt_username.setText(regdto.getUsername());
                txt_password1.setText(regdto.getPassword());
              
               byte[]image =regdto.getUserimage();
               formate=new ImageIcon(image);
                lblimage.setIcon(formate);
        } else{
        JOptionPane.showMessageDialog(this, "Id  Not Found ! Try Another");
        }
        
    }
     
  public void searchUserbyname(String EID) throws Exception {
       //RegistrationDTO regdto = ManageRegistrationController.searchRegistration(EID);
//        RegistrationDTO regdto = hashmapname.get(EID);
//        System.out.println("EID  "+EID+"    "+regdto);
//        
//            gender=regdto.getGender();
//            if(gender.equals("Male")){
//            btnradiomale.setSelected(true);
//            btnradiofemale.setSelected(false);
//            }else{
//             btnradiomale.setSelected(false);
//            btnradiofemale.setSelected(true);
//            }
//              txt_fullname.setText(regdto.getFname());
//             txt_lastname.setText(regdto.getLname());
//               
//              String date=regdto.getDob();
//              Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(date);
//              txtdatechooser.setDate(date1);
//                txt_email.setText(regdto.getEmail());
//                txt_phone.setText(Integer.toString(regdto.getPhone()));
//                txt_username.setText(regdto.getUsername());
//                txt_password1.setText(regdto.getPassword());
//              
//               byte[]image =regdto.getUserimage();
//               formate=new ImageIcon(image);
//                lblimage.setIcon(formate);
//             }else{
//        JOptionPane.showMessageDialog(this, "Full Name Not Found ! Try Another");
//        }
    }
  
  public void searchUserbyGender(String EID) throws Exception {
       //RegistrationDTO regdto = ManageRegistrationController.searchRegistration(EID);
//         DefaultTableModel dtm = (DefaultTableModel) tblstudents.getModel();
//         dtm.setRowCount(0);
//       RegistrationDTO regdto = hashmapgender.get(EID);
//        if (regdto != null) {
//            
//             Object [] row={allregs.getRegid(),allregs.getFname(),allregs.getLname(),allregs.getGender(),allregs.getDob(),allregs.getEmail(),allregs.getPhone(),allregs.getUserimage(),allregs.getPassword(),allregs.getUsername()};
//             dtm.addRow(row);
//            gender=regdto.getGender();
//            if(gender.equals("Male")){
//            btnradiomale.setSelected(true);
//            btnradiofemale.setSelected(false);
//            }else{
//             btnradiomale.setSelected(false);
//            btnradiofemale.setSelected(true);
//            }
//              txt_fullname.setText(regdto.getFname());
//             txt_lastname.setText(regdto.getLname());
//               
//              String date=regdto.getDob();
//              Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(date);
//              txtdatechooser.setDate(date1);
//                txt_email.setText(regdto.getEmail());
//                txt_phone.setText(Integer.toString(regdto.getPhone()));
//                txt_username.setText(regdto.getUsername());
//                txt_password1.setText(regdto.getPassword());
//              
//               byte[]image =regdto.getUserimage();
//               formate=new ImageIcon(image);
//                lblimage.setIcon(formate);
           //  }
//            else{
//        JOptionPane.showMessageDialog(this, "Type Gender Not Found ! Try Another");
//        }
    }
   
   private void clearfields(){
   txt_fullname.setText("");
       txt_lastname.setText("");
       txt_email.setText("");
      txt_phone.setText("");
        txt_regid.setText("");
        txt_username.setText("");
        txt_password.setText("");      
        txtdatechooser.setDate(null);
        txt_regid.setText("");
        txtimagepath.setText("");
        lblimage.setIcon(null);
        buttonGroup1.clearSelection();
        lbl_availability.setText("");
        
        useravailablity=false;
   
   }





}
